name: Generate Lighthouse Report

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Get Report
        run: |
          npm install -g lighthouse
          lighthouse https://brbousnguar.github.io/my-portfolio/ --chrome-flags="--headless" --output="json" --output-path="./report.json"
          cat ./report.json
